### ISSUE TITLE
Initial Unit Tests for Core Database Objects

### ISSUE THREAD

**Issue by PhilippSalvisberg** [PhilippSalvisberg/plscope-utils#22]
Create unit tests using [utPLSQL v3](https://github.com/utPLSQL) for [Core Database Objects](https://github.com/PhilippSalvisberg/plscope-utils/tree/master/database). 

Add the project to the CI server. See [utPLSQL-sql-cli](https://github.com/utPLSQL/utPLSQL-sql-cli)

**Comment by jgebal** [comment]
Have a look at [utPLSQL-cli](https://github.com/utPLSQL/utPLSQL-cli)
It's a Java based client that does not require SQLPlus.
It's much more powerful and will be maintained.
In near future we willl depreciate utPLSQL-sql-cli.

**Comment by PhilippSalvisberg** [comment]
Ah, even better. Thanks @jgebal for the tip.
