### ISSUE TITLE
How to check naming convention for constraint,PK,FK etc ..? Is their any provision ?

### ISSUE THREAD

**Issue by rajivgupta780184** [PhilippSalvisberg/plscope-utils#28]
How to check naming convention for constraint,PK,FK etc ..? Is their any provision ?

**Comment by PhilippSalvisberg** [comment]
The main scope for PL/Scope and also for plscope-utils is to deal with PL/SQL code within stored objects. 

If you want to check naming conventions for database objects such as tables, views, columns, indexes, constraints, etc. than you may do that querying data dictionary objects such as `dba_objects`, `dba_tables`, `dba_views`, dba_tab_columns`, `dba_indexes`, `dba_constraints`, etc.
