### ISSUE TITLE
Loop in Dependency Graph

### ISSUE THREAD

**Issue by zedage** [PhilippSalvisberg/plscope-utils#33]
On the tabs "Table Usages" and "Column Usages" I get a ORA-01436 (Connect By loop).
![plscope](https://user-images.githubusercontent.com/46347912/70420910-02422900-1a69-11ea-905c-8ca81cc13f76.png)

**Comment by PhilippSalvisberg** [comment]
Thank you, @zedage for this bug report. I consider this a bug. The query should deal with loops in the dependency graph. I plan to address that in one of the coming versions.

**Comment by PhilippSalvisberg** [comment]
use recursive with clause with cycle clause to solve this issue.

**Comment by PhilippSalvisberg** [comment]
fixed in all relational views and in SQLDev reports and SQLDev editors (viewers)
