### ISSUE TITLE
View not created with SQL*Plus from the Instant Client 18.5 bundle for Windows x64.

### ISSUE THREAD

**Issue by PhilippSalvisberg** [PhilippSalvisberg/plscope-utils#47]
see https://github.com/PhilippSalvisberg/plscope-utils/pull/46

**Comment by PhilippSalvisberg** [comment]
The PR #46 causes this new issue:

![image](https://user-images.githubusercontent.com/3883171/188579960-a11ab66e-59be-4c4f-8ba5-262c3e612d0a.png)

This is a limitation of the PL/SQL parser. See https://github.com/Trivadis/plsql-cop-cli/blob/main/parser-limitations.md#sqlplus-substitution-variables .

Undo the change of plscope_naming.sql and use single-line comments instead.

**Comment by rvo-cs** [comment]
Hi Philipp,

Noted: no tricks with SQL\*Plus substitution variables—except maybe in the SELECT-list or as a WHERE condition.

Unfortunately, the present fix is incomplete: here's the readout using SQL\*Plus:
```
====================================================================
Views
====================================================================

View created.

No errors.

View created.

No errors.

View created.

No errors.
      --       plscope_context.set_attr('GLOBAL_VARIABLE_REGEX',       '^(g|m)_.*')
                                                                                  *
ERROR at line 9:
ORA-00903: invalid table name


SP2-0042: unknown command "src as (" - rest of line ignored.
      ),
      *
ERROR at line 11:
ORA-00933: SQL command not properly ended


No errors.
```
Tested using SQL\*Plus 12.2 on Linux; 2 other versions/platforms that I have tested behave similarly. 

(Remark: this has prompted me to re-test the v1.0.0 installation, and I realized that the original issue also affected SQL\*Plus 12.2 and 19c on Linux, so perhaps it was not version/platform-specific, contrary to what I had figured initially.)

I'm filing another PR for a possible fix.

Regards,

**Comment by PhilippSalvisberg** [comment]
opened issue #53
