### ISSUE TITLE
plscope_ins_lineage view always returns an empty result set

### ISSUE THREAD

**Issue by OrdnasselaOttogim** [PhilippSalvisberg/plscope-utils#72]
plscope-utils is correctly installed, I am able to see as expected the results from all the others views (i.e. PLSCOPE_IDENTIFIERS, PLSCOPE_STATEMENTS, PLSCOPE_TAB_USAGE, PLSCOPE_COL_USAGE) except _plscope_ins_lineage_, which no matter what returns always an empty Result Set (0 rows). 
It does not work either using the demo code present in the repository (LOAD_FROM_TAB etc.), of which tokens are correctly displayed on all the other views instead. 
No error messages, just zero rows. 
Is there any chance that you know what can the issue be? @PhilippSalvisberg 

Thank you in advance.

**Comment by PhilippSalvisberg** [comment]
Do you have access to `UTL_XML`, `UTL_XML_LIB`? - They are not available in cloud environments. See also

https://github.com/PhilippSalvisberg/plscope-utils/blob/v1.0.0/database/install.sql#L119-L122

**Comment by OrdnasselaOttogim** [comment]
Yes, I believe that was the issue. Now the view works as intended. 
Thank you.
